### PR TITLE
Add Ethereum to thumbnail copy

### LINKED ISSUE #88: Add "Ethereum" on the thumbnail
image

It should say: Ethereum ecosystem

cc @andrealbiac

### PR DESCRIPTION
**Pull request by Pabl0cks**
## Description

Add "Ethereum" copy to thumbnail => "Funding meaningful projects across the Ethereum ecosystem"

## Related Issues

Closes #88

### CODE REVIEW

**Comment by carletex** [comment]
image

Oh, that `p` almost touching the `E` looks a bit weird, right?

Maybe this will fix?

image

or more space between the lines?

Not sure, open to suggestions!

**Comment by Pabl0cks** [comment]
I've tried some options here:

| thumbnail1 | thumbnail2 |
|--------------------------------------|--------------------------------------|
| thumbnail3 | thumbnail4 |

My personal feedback for each option.
- 1 looks a bit strange to me, but maybe because I'm not used to it. It's true that in meta-descriptions it's very common to see sentences like that.
- 2 looks well to me, and capitalize "Projects" may make sense like if we want to emphasize they are not "regular" projects.
- 3 looks well but is hard to find a word that has all the meaning of "projects". Ideas or builds may not match well for all the stuff we grant.
- 4 still looks a bit weird to me the separation between the `p` and `E`

**Comment by carletex** [comment]
Thanks Pablo!! 

I think I like **2** too.

**Comment by Pabl0cks** [comment]
> I think I like 2 too.

Thx! Just pushed **2** 🙌

**Pull request merged**
