### PR TITLE
Community Grants section - Customize apply button and feedback depending on connected address

### LINKED ISSUE #66: Add a visual element to Community Grants section to show extra info depending on user status
Similar to what we're doing in SRE showing "Quest" to open challenges or "Locked" + icon with tooltip to closed challenges based on your builder status, we want to show extra info to:

- **Wallet not connected**: Ask the user to connect the wallet in order to check if he's in the BuidlGuidl or not, explaining he needs to be in BG to apply for a grant.
- **Wallet connected but not a BG member**: Suggest the user to make SRE in order to join BG and be able to apply for grants.
- **Wallet connected, BG member**: Explain that he can apply for grants because he is a BG member.

This has to be very visual and accomplish 2 main goals, drive non BG users to join BG through SRE, and make it more obvious that is a perk only to BG members.

For the logic, we'll just need to migrate it from `/apply` page ("Submit button") to the Community Grants section.

<details>
<summary>Here is the SRE button example</summary>

image

</details>

### PR DESCRIPTION
**Pull request by Pabl0cks**
Fixes #66

A few notes to check:

- Changed warning and success color tones to match the design, since they were mostly used in Admin pages, that way don't need to define a new color manually for this. (Not sure if that's the right practice tho!)
- Created a new component just to leave all the "messy" conditions there.
- Created a "fake" button for non-bg members, and kept the `<Link>` for BG members, not sure if that's a good practice.
- At some point I thought it may be a good idea to fix the "Connect" header so you don't have to scroll up to connect, but then I thought that would not be the common use case, and discarded the idea. LMK if you think is needed! 🙌

Hope the code is not too messy, sorry just in case lol

https://www.loom.com/share/baf0788d88514003bc5c1513b2b50f1d?sid=aa38c661-61c3-44a5-8755-b1b2209860d7

### CODE REVIEW

**Comment by Pabl0cks** [comment]
> Changed warning and success color tones to match the design, since they were mostly used in Admin pages, that way don't need to define a new color manually for this. (Not sure if that's the right practice tho!)

I think I'm going to revert that one, the green color looks really bad in some admin actions 😢

**Review by technophile-04 — APPROVED** [review]
Tysm @Pabl0cks !! Working great ! Just pushed a couple commits : 

1. Cleand / simplified it a bit: inlined the logic for ApplyButton and created FeedBackMessage component just to avoid lot ternaries in parent component itself
2. Centered the "Do you Qualify?" box on mobile 
3. Allowed people to connect to wallet from Communtiy Grants sections itself and also added a loader while we are fetching buildersData to from backend to check for eligibility (The on local firebase instance was close to none but on prod there is  very small delay) 

<details>
<summary>
Demo video : 
</summary>

https://github.com/BuidlGuidl/grants.buidlguidl.com/assets/80153681/c92935bd-fba1-4dde-96ff-8a6732c9f9c4

</details>

--- 

Also a small nitpick : Should we decrease padding a bit of left section so that it decrease the height of whole Community section ? 

https://github.com/BuidlGuidl/grants.buidlguidl.com/blob/b26c43b61fb48beb9bfaa196e4cfb8e498c3a216/packages/nextjs/app/_components/CommunityGrant.tsx#L9

Because currently the patches in the right section (Who, Process, Amount etc) seems a bit apart from each other 

But yeah maybe we could handle it in different PR 🙌

**Comment by carletex** [comment]
This is great! Thank you both <33

Pushed a couple of little things. One is to make this better: 

> Because currently the patches in the right section (Who, Process, Amount etc) seems a bit apart from each other

We can iterate in another PR (still some resolution around 1100 when the patches overlap)

**Comment by Pabl0cks** [comment]
Thanks @technophile-04 and @carletex for the review!! This one was tough, sorry you had to get your hands dirty!! 😢

Your implementation is much cleaner Shiv, love it!! ❤

**Pull request merged**
