### PR TITLE
Update featured grants images to fix aspect ratio

### LINKED ISSUE #114: Featured grants image aspect ratios
Right now the thumbnails for Featured grants look squashed down

photo_2024-04-17 15 13 50

Gonna change the aspect ratio of these and see if that fixes the problem ✌🏻

### PR DESCRIPTION
**Pull request by Pabl0cks**
Fixes #114 

Haven't used the biggest version of Jessy's because probably we don't need super definition on people's faces, and that way overall image size doesn't grow much.

Adding a couple of screenshots so you can check if everything looks OK @andrealbiac 

Screenshot post update on laptop:

image

Screenshot post update on desktop (with some zoom):

image

### CODE REVIEW

**Comment by carletex** [comment]
I remember this happening before: A pixel around the images. I think it was related to some shadow applied on Figma.

image

**Review by andrealbiac — CHANGES_REQUESTED** [review]
True the damn shadow. Yeah at first we thought it was a shadow effect in Figma but it wasn't that, we didn't find the reason and I ended up making screenshots of it 🤓 But I completely forgot about that, thanks for noticing Carlos!

I still can't find why that happens so let's upload screenshots again. No need to review after this cause the quality looks fine 🫡 

So I'll just send them here: (hope it makes sense to add it in the review - first time reviewing a PR)

bytes032 eth
erhant eth
jtriley eth
w1nt3r-evm
solidity-by-example
jessys-hacker-house

Thanks guys!!

**Comment by Pabl0cks** [comment]
Thanks @carletex for the good eye and @andrealbiac for the updated assets. I forgot about that problem and thought the empty border was intended, sorry! 😓

I've just updated them with the last ones, compacted them a bit to reduce the file size.

**Review by andrealbiac — APPROVED** [review]
All good. And yeah it's so difficult to see that! I also didn't notice the first time lol

 Thanks Pablo! 😊

**Pull request merged**
